### ISSUE TITLE
Breaking change in 4.1.0: can't require @shelf/jest-mongodb/setup

### ISSUE THREAD

**Issue by ArthurHoaro** [shelfio/jest-mongodb#378]
I use a simple jest setup script to perform a few bootstrap operations (init, load fixtures, etc.), based on #212, something like this:

```js
const mongoSetup = require('@shelf/jest-mongodb/setup');

module.exports = async() => {
    await mongoSetup();

    // Do stuff with MONGO_URL
};
```

Unfortunately, this no longer works with the release `v4.1.0`, but it did work with `v4.0.0`. The following error is now thrown:

```
Error: Jest: Got error running globalSetup - /home/<path>/jest-setup.js, reason: Cannot find module '@shelf/jest-mongodb/setup'
``` 

I don't mind updating my script if it's an expected behavior, but since it does not seem to be documented, I'm not sure what's the best way to handle it.

```
 ➜ node -v     
v16.17.0
 ➜ npm -v      
8.15.0
```

**Comment by vladgolubev** [comment]
```
const mongoSetup = require('@shelf/jest-mongodb/lib/setup');
```

Have you tried this?

**Comment by ArthurHoaro** [comment]
I did not, and it's working fine! Thank you! I suppose it's because the build has changed with TS support. 

It could be worth mentioning it in the release note.
